[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "etl"
version = "0.1.0"
description = "ETL core package"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["etl*"]

